{{ $credentials := include "sentry.clickhouse.credentials" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-env
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  CLICKHOUSE_PORT: {{ include "sentry.clickhouse.port" . | b64enc | quote }}
  CLICKHOUSE_DATABASE: {{ include "sentry.clickhouse.database" . | b64enc | quote }}
  {{- if hasKey $credentials "name" }}
  CLICKHOUSE_USER: {{ print $credentials.name | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.externalClickhouse.existingSecret) (hasKey $credentials "password") }}
  CLICKHOUSE_PASSWORD: {{ print $credentials.password  | b64enc | quote }}
  {{- end }}